# pyproject.toml
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -vv"
testpaths = [
    "tests",
    "integration",
]

[tool.flake8]
exclude = [".venv", "build"]
max-line-length = 79


[tool.black]
line-length = 79
target-vesion = ["py38", "py.39"]
exclude = '''
/(
      \.eggs
    | \.git
    | \.venv
    | _build
    | build
    | dist
    | migrations
)/
'''

[tool.isort]
profile = "black"
src_paths = ["dundie", "tests", "integration"]
multi_line_output = 3
